version: 2
jobs:
  build_php:
    docker:
     - image: circleci/php
          
    steps:
     - checkout
  test:
    docker:
     - image: circleci/php
     - image: mysql
       environment:
        MYSQL_ROOT_PASSWORD: '@connectme'
    steps:
     - checkout
     - run: sudo apt update
     - run: sudo apt install mysql-client -y
     - run: dockerize -wait tcp://localhost -timeout 2m
     - run: curl http://localhost/create_database.php
  docker_push:
    docker:
     - image: circleci/php
    steps:
     - checkout
     - setup_remote_docker
     - run: docker login -u 'bgamil' -p 'Dockerhub*0611'
     - run: docker build -t bgamil/docker_project .
     - run: docker push bgamil/docker_project

workflows:
  version: 2
  build_and_test:
    jobs:
     - build_php
     - test:
        requires:
          - build_php
     - docker_push:
        requires:
          - test